### ISSUE TITLE
How to pass outputs from stackA as props to stackB

### ISSUE THREAD

**Issue by RaeesBhatti** [pahud/cdk-remote-stack#177]
Is it possible to use outputs from `stackA` as props to `stackB`. If so, how can this be done?

Thanks!

**Comment by pahud** [comment]
Unfortunately, not possible and not in the roadmap at this moment. Please check the README for the sample. Thanks.

**Comment by Jonathan-Eid** [comment]
I got it to work by having a stack in the middle, is there anything wrong with this approach @pahud  ?

const env1= { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'us-east-1' };

const env2= { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'us-east-2' };

const app = new cdk.App();

const env1_stack= new Env1Stack(app, "NodeStack", {env: env1})
new cdk.CfnOutput(env1_stack, 'whatever1', { value: env1_stack.whatever1})
new cdk.CfnOutput(env1_stack, 'whatever2', { value: env1_stack.whatever2})


const middle_stack= new MiddleStack(app, 'MiddleStack', {env: env2});

middle_stack.addDependency(env1_stack)

const outputs = new StackOutputs(net_stack, 'Outputs', { stack: env1_stack})

const whatever1= outputs.getAttString("whatever1")
const whatever2= outputs.getAttString("whatever2")


const env2_stack= new Env2Stack(app, 'devNetECS', {env: env2, 
                                whatever1,
                                whatever2
                            });

**Comment by Jonathan-Eid** [comment]
I got it to work by having a stack in the middle, is there anything wrong with this approach @pahud ?

const env1= { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'us-east-1' };

const env2= { account: process.env.CDK_DEFAULT_ACCOUNT, region: 'us-east-2' };

const app = new cdk.App();

const env1_stack= new Env1Stack(app, "NodeStack", {env: env1})
new cdk.CfnOutput(env1_stack, 'whatever1', { value: env1_stack.whatever1})
new cdk.CfnOutput(env1_stack, 'whatever2', { value: env1_stack.whatever2})

const middle_stack= new MiddleStack(app, 'MiddleStack', {env: env2});

middle_stack.addDependency(env1_stack)

const outputs = new StackOutputs(net_stack, 'Outputs', { stack: env1_stack})

const whatever1= outputs.getAttString("whatever1")
const whatever2= outputs.getAttString("whatever2")

const env2_stack= new Env2Stack(app, 'Env2Stack', {env: env2,
whatever1,
whatever2
});
