### ISSUE TITLE
CDK v2 support

### ISSUE THREAD

**Issue by ahammond** [pahud/cdk-remote-stack#426]
This looks great, and I'd like to use it with CDKv2. I think all that's involved in that is upgrading to the latest greatest  version of the Constructs library, but... ?

**Comment by pahud** [comment]
@ahammond Thanks for the feedback.  This package currently support CDK v1 only and has explicit dependencies on other V1 packages:

https://github.com/pahud/cdk-remote-stack/blob/fc63a9ebf146c1da0da738dce200580af681c0e3/.projenrc.js#L38-L44

To support V2, I believe we remove all the V1 dependencies and depend a single V2 library only. Looks like we can only opt in either of them not both.

I personally prefer we opt in V1 until V2 is stable.

WDYT?

@alexpulver @neilkuan

**Comment by alexpulver** [comment]
I need to dive deeper into this, but from the top of my head - split the code base into three parts. Extract code that doesn't have any dependency on CDK or doesn't depend on code that is different between CDK v1 and v2 into shared module(s). The rest should go into `v1` and `v2` directories. Each will have their own set of dependencies. When making changes, do it first for v2, and then backport to v1 if possible. The publishing process can stay the same I think, just publish v1 and v2 (can be sensitive to whether the change is only in one of them)

**Comment by ahammond** [comment]
So... CDKv2 is GA as of last week. :)
